### ISSUE TITLE
`tableView: didSelectRowAtIndexPath:` not being forwarded from `ALTableViewCellFactory`

### ISSUE THREAD

**Issue by AnthonyMDev** [JRG-Developer/AutoLayoutCells#8]
I'm not sure if I'm doing something wrong, but I cannot get `tableViewDidSelectRowAtIndexPath` to be forwarded from the factory to my view controller.

**Comment by JRG-Developer** [comment]
Done. Added to CocoaPods as version `0.6.1`.
